GET http://localhost:3000/api/Usuarios HTTP/1.1

### 
GET http://localhost:3000/api/Usuarios/2 HTTP/1.1

### 
POST http://localhost:3000/api/Usuarios HTTP/1.1
content-type: application/json

{
"Id": 1,
"Nombre":"Angel"    ,
"NombreUsuario":"AngelCruz2001"     ,
"Edad":  17,
"Domicilio": "En su casita",
"Celular":  "6183259226",
"ContactoEmergencia":  "6181092045",
"Genero":  "Hombre",
"UbicacionActual":  "DurangoYork",
"LugarReciente":"Itecor"
}
### 
DELETE  http://localhost:3000/api/Usuarios/2 HTTP/1.1

### 
PUT http://localhost:3000/api/Usuarios/2 HTTP/1.1
content-type: application/json

 {
    "Nombre": "Eric",
    "NombreUsuario": "TeacherEric",
    "Edad": 26,
    "Domicilio": "En su casita",
    "Celular": "6181092045",
    "ContactoEmergencia": "6183259226",
    "Genero": "indefinido",
    "UbicacionActual": "DurangoYork",
    "LugarReciente": "Itecor"
  }
###
GET  http://localhost:3000/api/Lugares/Paseo Durango HTTP/1.1

### 
GET http://localhost:3000/api/LugaresFav HTTP/1.1
###
POST http://localhost:3000/api/Lugares HTTP/1.1
content-type: application/json.
 
{
  "Nombre":"Paseo Durango",
  "Ubicacion":"DurangYork",
  "Horario":{
      "Apertura":"11:00",
      "Cierre":"21:00"
  }
}
###
POST http://localhost:3000/api/LugaresFav HTTP/1.1
content-type: application/json.

{
  "Nombre":"Paseo Durango",
  "UserName":"AERM2018"
} 
###
DELETE  http://localhost:3000/api/LugaresFav/Las vegas2 HTTP/1.1
