GET http://localhost:3000/api/Usuarios HTTP/1.1

### 
GET http://localhost:3000/api/Usuarios/2 HTTP/1.1

### 
POST http://localhost:3000/api/Usuarios HTTP/1.1
content-type: application/json

{
"Id": 2,
"Nombre":"Angel"    ,
"NombreUsuario":"Angel"     ,
"Edad":  17,
"Domicilio": "Paseo del Alamo",
"Celular":  "6183259226",
"ContactoEmergencia":  "6182209340",
"Genero":  "Masculino",
"UbicacionActual":  "Durango"
}
### 
DELETE  http://localhost:3000/api/Usuarios/2 HTTP/1.1

### 
PUT http://localhost:3000/api/Usuarios/2 HTTP/1.1
content-type: application/json

{
"Nombre":"AngelUpdate",
"NombreUsuario":"AngelUpdate"     ,
"Edad":  17,
"Domicilio": "Paseo del AlamoUpdate",
"Celular":  "6183259226Update",
"ContactoEmergencia":  "6182209340Update",
"Genero":  "MasculinoUpdate",
"UbicacionActual":  "DurangoUpdate"
}
